const fakeData = [
  {
    house_id: 100,
    name: 'Amira',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/magugzbrand2d/128.jpg',
    created: '2018-06-16T07:00:00.000Z',
    review: 'Ex illo est blanditiis eum nulla nulla deserunt. Praesentium aut velit exercitationem consequuntur delectus error tempore. Facilis quo qui.',
    host_comments: 'Non consequatur eum ut qui quasi.',
    rating: 3,
  },
  {
    house_id: 100,
    name: 'Jaren',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/wegotvices/128.jpg',
    created: '2018-05-26T07:00:00.000Z',
    review: 'Necessitatibus eum similique. Repudiandae quaerat aspernatur possimus eum ut. Eum aspernatur omnis omnis nulla iure.',
    host_comments: 'null',
    rating: 3,
  },
  {
    house_id: 100,
    name: 'Queen',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/laasli/128.jpg',
    created: '2018-05-06T07:00:00.000Z',
    review: 'Facere recusandae sint. Quibusdam laudantium perferendis eaque velit fugit. Tempore dicta dolores enim earum. Debitis quibusdam consectetur corporis aut est.',
    host_comments: 'null',
    rating: 1,
  },
  {
    house_id: 100,
    name: 'Charley',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/markjenkins/128.jpg',
    created: '2018-03-18T07:00:00.000Z',
    review: 'Sit tempore esse porro aut nihil voluptatem repellat ab. Numquam soluta perspiciatis quia quia quae et odio. Et eum aut non dolorum laborum est quia. Et cum qui quisquam ipsa minima eos velit unde similique. Laudantium eos sed animi ea aperiam fugit nihil.',
    host_comments: 'null',
    rating: 4,
  },
  {
    house_id: 100,
    name: 'Edwina',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/runningskull/128.jpg',
    created: '2018-02-24T08:00:00.000Z',
    review: 'Veniam perspiciatis dolor enim quis sit quas. Error esse est quam labore omnis voluptate ut deserunt. Ut harum dolore dignissimos possimus quis a.',
    host_comments: 'null',
    rating: 5,
  },
  {
    house_id: 100,
    name: 'Catharine',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/lawlbwoy/128.jpg',
    created: '2018-02-15T08:00:00.000Z',
    review: 'Quia expedita dolor quos corporis aperiam earum at sunt vel. Totam a ut in dolore enim. Sunt et deleniti quaerat quia nesciunt reiciendis est est. Repudiandae quo sequi animi quia et.',
    host_comments: 'null',
    rating: 2,
  },
  {
    house_id: 100,
    name: 'Sallie',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/michaelmartinho/128.jpg',
    created: '2017-12-29T08:00:00.000Z',
    review: 'Fuga est illo excepturi distinctio ducimus expedita. Id voluptatem nostrum. Harum voluptatibus perspiciatis est nesciunt rerum ut vero et iure. Delectus libero tempore saepe quos ut ut repellendus eligendi sequi.',
    host_comments: 'null',
    rating: 4,
  },
  {
    house_id: 100,
    name: 'Assunta',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/adhamdannaway/128.jpg',
    created: '2017-12-24T08:00:00.000Z',
    review: 'Hic numquam beatae laborum rerum et qui et. Aliquam tempore consectetur qui. Aut eos magnam consequuntur omnis vel non molestias. Iste consectetur omnis quasi expedita non. Quos aut ea.',
    host_comments: 'Et at nesciunt distinctio non quos in placeat.',
    rating: 1,
  },
  {
    house_id: 100,
    name: 'Peter',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/shanehudson/128.jpg',
    created: '2017-12-02T08:00:00.000Z',
    review: 'Deleniti reiciendis aperiam deserunt inventore veniam cupiditate ut et. Veritatis nisi maxime sed aut porro totam voluptatem sapiente excepturi. Ut est et iure voluptatibus facere.',
    host_comments: 'null',
    rating: 4,
  },
  {
    house_id: 100,
    name: 'Lavina',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/reideiredale/128.jpg',
    created: '2017-10-22T07:00:00.000Z',
    review: 'Molestiae illo quia sequi quia. Dicta accusantium voluptas voluptates repudiandae voluptatem beatae consequatur magni officia. Nihil iure iusto non. Sed sapiente repellat blanditiis rerum eius totam et facilis. Iusto impedit eos omnis. Provident repudiandae velit aspernatur.',
    host_comments: 'null',
    rating: 5,
  },
  {
    house_id: 100,
    name: 'Queen',
    photo: 'https://s3.amazonaws.com/uifaces/faces/twitter/laasli/128.jpg',
    created: '2017-09-26T07:00:00.000Z',
    review: 'Laudantium in illum est modi magnam natus. Ipsa totam architecto consequatur voluptatem. Qui dolores eos in sit praesentium. Doloribus accusamus numquam incidunt aut libero animi hic delectus non. Id qui necessitatibus. Aspernatur enim veniam quas cupiditate.',
    host_comments: 'null',
    rating: 2,
  },
];
module.exports.fakeData = fakeData;
